package com.example.todoproject.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.LocalTime
import java.time.format.DateTimeFormatter

/**
 * Represent a task in the database
 * This data class defines the structure of a task entity (table) that will be stored in the Room database.
 * @param id The unique identifier for the task, auto-generated by the database.
 * @param title The title of the task.
 * @param description A detailed description of the task.
 * @param date The date associated with the task, stored as a string.
 * @param status The current status of the task.
 */
@Entity(tableName = "Tasks")
data class TaskEntity(

    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    @ColumnInfo(name = "title")
    val title: String,

    @ColumnInfo(name = "description")
    val description: String,

    @ColumnInfo(name = "date")
    val date: String,

    @ColumnInfo(name = "hours")
    val hours: String,

    @ColumnInfo(name = "status")
    val status: String
) {
    fun isLate(): Boolean {
        if (status != "En cours") {
            return false
        }

        val date = LocalDate.parse(this.date)
        val now = LocalDate.now()

        if (date.isBefore(now)) {
            return true
        }

        if (date.isEqual(now)) {
            val timeFormatter = DateTimeFormatter.ofPattern("HH:mm")
            val taskTime = LocalTime.parse(hours, timeFormatter)
            val currentTime = LocalTime.now()
            if (taskTime.isBefore(currentTime)) {
                return true
            }
        }

        return false
    }
}