package com.example.todoproject.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.LocalTime
import java.time.format.DateTimeFormatter

/**
 * Represent a task in the database
 * This data class defines the structure of a task entity (table) that will be stored in the Room database.
 * @param id The unique identifier for the task, auto-generated by the database.
 * @param title The title of the task.
 * @param description A detailed description of the task.
 * @param date The date associated with the task, stored as a string.
 * @param status The current status of the task.
 */
@Entity(tableName = "Tasks")
data class TaskEntity(

    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    @ColumnInfo(name = "title")
    val title: String,

    @ColumnInfo(name = "description")
    val description: String,

    @ColumnInfo(name = "date")
    val date: String,

    @ColumnInfo(name = "hours")
    val hours: String,

    @ColumnInfo(name = "status")
    val status: String,

    @ColumnInfo(name = "periodicity")
    val periodicity: String = "Aucune"
) {
    fun isLate(): Boolean {
        if (status != "En cours") {
            return false
        }

        val date = LocalDate.parse(this.date)
        val now = LocalDate.now()

        if (date.isBefore(now)) {
            return true
        }

        if (date.isEqual(now)) {
            val timeFormatter = DateTimeFormatter.ofPattern("HH:mm")
            val taskTime = LocalTime.parse(hours, timeFormatter)
            val currentTime = LocalTime.now()
            if (taskTime.isBefore(currentTime)) {
                return true
            }
        }

        return false
    }

    suspend fun changeDate(taskEntity: TaskEntity, repository: OfflineTaskRepository) {

        // get the date and the today date
        var newDate = LocalDate.parse(taskEntity.date)
        val now = LocalDate.now()

        // change the date of the task depending on its periodicity until the date is after the today date
        while (!newDate.isAfter(now)) {
            newDate = when (taskEntity.periodicity) {
                "Quotidienne"  -> newDate.plusDays(1)
                "Hebdomadaire" -> newDate.plusWeeks(1)
                "Mensuelle"    -> newDate.plusMonths(1)
                else           -> break.let { return }
            }
        }

        // update the task with the new date and the status "En cours"
        repository.updateTask(
            TaskEntity(
                id = taskEntity.id,
                title = taskEntity.title,
                description = taskEntity.description,
                date = newDate.toString(),
                hours = taskEntity.hours,
                status = "En cours",
                periodicity = taskEntity.periodicity
            )
        )
    }
}